dist: xenial

language: python

python:
- 3.5
- 3.6
- 3.7
- 3.8

install:
- pip install coveralls
- pip install pylint
- pip install pytest
- pip install pytest-cov
- pip install pytest-mock
- pip install mock
- pip install mypy

script:
- pylint bin/chroma-feedback chroma_feedback tests
- mypy bin/chroma-feedback chroma_feedback tests
- travis_retry pytest tests --cov=chroma_feedback

after_success:
- coveralls
